rpc:
  host: 0.0.0.0
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
governance:
  timeoutMillSeconds: 0  
registrycenter:
  connectionStrings: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183;127.0.0.1:2184,127.0.0.1:2185,127.0.0.1:2186
  type: Zookeeper
  scheme: Digest
  auth: "silky:pass4Word"  
distributedCache:
  redis:
    isEnabled: true
    configuration: 127.0.0.1:6379,defaultDatabase=0
gateway:
  jwtSecret: jv1PZkwjLVCEygM7faLLvEhDGWmFqRUW
swaggerDocument:
  termsOfService: https://www.github.com/liuhll/silky
  showDashboardService: false

dashboard:
  tenantNameFiledName: tenantName
  userNameFiledName: account
  passwordFiledName: password
  dashboardLoginApi: /api/account/login
  externalLinks:
    - title: "message.swagger"
      path: "http://localhost:5002"
      icon: "iconfont icon-swagger"
    - title: "SkyWalking"
      path: "http://localhost:8180"
    - title: "Github"
      path: "https://github.com/liuhll/silky"
      icon: "iconfont icon-github"
    - title: "Gitee"
      path: "https://gitee.com/liuhll2/silky"
      icon: "iconfont icon-gitee2"